language: go

go:
  - 1.13
  - tip

before_install:
   - go get github.com/mattn/goveralls
   - go get golang.org/x/tools/cmd/cover
   - sudo cp config-sample.json config.json

env:
  - GO111MODULE=on

script:
   - goveralls -service=travis-ci
