version: '3'
services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/moemoe89/practicing-mongodb-golang
    container_name: practice_mongodb_app
    restart: always
    ports:
      - "8786:8786"
    tty: true
    depends_on:
      - mongodb
    networks:
      - fullstack
  mongodb:
    image: mongo:latest
    container_name: practice_mongodb_db
    environment:
      MONGO_INITDB_DATABASE: practice_mongodb
    restart: always
    ports:
      - "27016:27017"
    tty: true
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge