// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import form "github.com/moemoe89/go-mongodb-gita/api/api_struct/form"
import mock "github.com/stretchr/testify/mock"
import model "github.com/moemoe89/go-mongodb-gita/api/api_struct/model"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// UserCreate provides a mock function with given fields: ctx, user
func (_m *Service) UserCreate(ctx context.Context, user *form.UserForm) (*model.UserModel, int, error) {
	ret := _m.Called(ctx, user)

	var r0 *model.UserModel
	if rf, ok := ret.Get(0).(func(context.Context, *form.UserForm) *model.UserModel); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserModel)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, *form.UserForm) int); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *form.UserForm) error); ok {
		r2 = rf(ctx, user)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserDelete provides a mock function with given fields: ctx, id
func (_m *Service) UserDelete(ctx context.Context, id string) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserFind provides a mock function with given fields: ctx
func (_m *Service) UserFind(ctx context.Context) ([]*model.UserModel, int, error) {
	ret := _m.Called(ctx)

	var r0 []*model.UserModel
	if rf, ok := ret.Get(0).(func(context.Context) []*model.UserModel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserModel)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserFindByID provides a mock function with given fields: ctx, id
func (_m *Service) UserFindByID(ctx context.Context, id string) (*model.UserModel, int, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.UserModel
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserModel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserModel)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserUpdate provides a mock function with given fields: ctx, user, id
func (_m *Service) UserUpdate(ctx context.Context, user *form.UserForm, id string) (*model.UserModel, int, error) {
	ret := _m.Called(ctx, user, id)

	var r0 *model.UserModel
	if rf, ok := ret.Get(0).(func(context.Context, *form.UserForm, string) *model.UserModel); ok {
		r0 = rf(ctx, user, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserModel)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, *form.UserForm, string) int); ok {
		r1 = rf(ctx, user, id)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *form.UserForm, string) error); ok {
		r2 = rf(ctx, user, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
